name: Deployment

on:
  check_run:
    types: [completed]    
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    #NOTE: need to check that ALL analyses are completed via check_run.status != 'neutral' here since there is no other indicators (aside from output.title: "1 analysis not found") -> check_run.status: "completed" && check_run.conclusion: "success" 
    if: ${{ github.event.check_run.name == 'CodeQL' && github.event.check_run.conclusion != 'neutral'}}
    environment: 
      name: Development
      url: https://github.com
    steps:
        #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#check_run
      - name: CodeQL Check Summary
        run: |
          echo ${{ github.event.check_run.output.title }}
      - name: CodeQL Check Suceeded - deploy
        if: ${{ github.event.check_run.conclusion == 'success' }}
        run: |
          echo 'Deploying... '
      - name: CodeQL Check Failed - no deploy
        if: ${{ github.event.check_run.conclusion == 'failure' }}
        run: |
          echo 'NOT deploying... '
          exit 1
