name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: https://github.com
    steps:
      - name: deploy
        run: |
          echo 'Deploying... '     
